Connected to Python 3.11.9

In [1]:
import pandas as pd 
import numpy as np

#Leer los archivos CSV (ventas.csv, productos.csv, clientes.csv).
df_ventas = pd.read_csv("../files/ventas.csv")
df_ventas.head()

   ID_Cliente ID_Producto Fecha_Venta  Cantidad  Total
0         723          A1  2023-11-22         2  17.98
1         498          C3  2023-11-21         1   5.49
2         121          D4  2023-11-20         3  32.97
3         885         L12  2023-11-19         1   6.49
4         347         Q17  2023-11-18         2   7.98

In [2]:
df_ventas.isnull().sum()

ID_Cliente     0
ID_Producto    0
Fecha_Venta    0
Cantidad       0
Total          0
dtype: int64

In [3]:
df_productos = pd.read_csv("../files/productos.csv",on_bad_lines='skip')
df_productos.head()

,ID,Nombre_Producto,Categoría,Precio,Origen,Descripción
A1,Pizza Margherita,Platos Preparados,8.99,Italia,Clásica pizza italiana con tomate,mozzarella fresca y albahaca.
B2,Risotto de Champiñones,Platos Preparados,6.75,Italia,Risotto cremoso con champiñones frescos,una delicia italiana para disfrutar en casa.
C3,Tiramisú,Postres,5.49,Italia,Postre clásico italiano con capas de bizcocho ...,mascarpone y cacao en polvo.
D4,Panettone,Repostería,10.99,Italia,Pan dulce navideño italiano con frutas confita...,un regalo tradicional en Italia.
E5,Orecchiette,Productos Secos,4.29,Italia,Pequeñas pastas con forma de orecchiette ideal...,NaN

In [4]:
df_ventas.info()


df_productos.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   ID_Cliente   100 non-null    int64
 1   ID_Producto  100 non-null    object
 2   Fecha_Venta  100 non-null    object
 3   Cantidad     100 non-null    int64
 4   Total        100 non-null    float64
dtypes: float64(1), int64(2), object(2)
memory usage: 4.0+ KB

ID                 0
Nombre_Producto    0
Categoría          0
Precio             0
Origen             0
Descripción        1
dtype: int64

In [5]:
df_clientes = pd.read_csv("../files/clientes.csv")
df_clientes.head()

df_clientes.isnull().sum()

id              0
first_name      0
last_name       0
email          27
gender         77
City          124
Country       154
Address        41
dtype: int64

In [6]:
df_clientes = pd.read_csv("../files/clientes.csv")
df_clientes.head()

,id,first_name,last_name,email,gender,City,Country,Address
0,1,Cheri,Dunsmore,cdunsmore0@instagram.com,Female,Palma De Mallorca,Spain,076 Rockefeller Crossing
1,2,Hunt,Bartomeu,hbartomeu1@nsw.gov.au,Male,Lugo,Spain,0046 Utah Junction
2,3,Michaeline,Paynton,mpaynton2@narod.ru,Female,NaN,Spain,0 Corry Crossing
3,4,Filmer,Eirwin,feirwin3@intel.com,NaN,Leon,Spain,5 American Ash Road
4,5,Tanhya,Lubbock,tlubbock4@huffingtonpost.com,Female,"Hospitalet De Llobregat, L'",Spain,9289 Merry Circle

In [7]:
df_clientes.isnull().sum()

id              0
first_name      0
last_name       0
email          27
gender         77
City          124
Country       154
Address        41
dtype: int64

In [8]:
df_clientes.columns()

TypeError: 'Index' object is not callable

In [9]:
df_clientes.columns

Index(['id', 'first_name', 'last_name', 'email', 'gender', 'City', 'Country',
       'Address'],
      dtype='object')

In [10]:
df_productos.isnull().sum()

ID                 0
Nombre_Producto    0
Categoría          0
Precio             0
Origen             0
Descripción        1
dtype: int64

In [11]:
df_productos['Descripción'] = df_productos['Descripción'].replace(999,np.nan)

In [12]:
df_productos.isnull().sum()

ID                 0
Nombre_Producto    0
Categoría          0
Precio             0
Origen             0
Descripción        1
dtype: int64

In [13]:
df_productos = pd.read_csv("../files/productos.csv",on_bad_lines='skip')
df_productos.head()

,ID,Nombre_Producto,Categoría,Precio,Origen,Descripción
A1,Pizza Margherita,Platos Preparados,8.99,Italia,Clásica pizza italiana con tomate,mozzarella fresca y albahaca.
B2,Risotto de Champiñones,Platos Preparados,6.75,Italia,Risotto cremoso con champiñones frescos,una delicia italiana para disfrutar en casa.
C3,Tiramisú,Postres,5.49,Italia,Postre clásico italiano con capas de bizcocho ...,mascarpone y cacao en polvo.
D4,Panettone,Repostería,10.99,Italia,Pan dulce navideño italiano con frutas confita...,un regalo tradicional en Italia.
E5,Orecchiette,Productos Secos,4.29,Italia,Pequeñas pastas con forma de orecchiette ideal...,NaN

In [14]:
df_clientes = pd.read_csv("../files/clientes.csv")
df_clientes.head()

,id,first_name,last_name,email,gender,City,Country,Address
0,1,Cheri,Dunsmore,cdunsmore0@instagram.com,Female,Palma De Mallorca,Spain,076 Rockefeller Crossing
1,2,Hunt,Bartomeu,hbartomeu1@nsw.gov.au,Male,Lugo,Spain,0046 Utah Junction
2,3,Michaeline,Paynton,mpaynton2@narod.ru,Female,NaN,Spain,0 Corry Crossing
3,4,Filmer,Eirwin,feirwin3@intel.com,NaN,Leon,Spain,5 American Ash Road
4,5,Tanhya,Lubbock,tlubbock4@huffingtonpost.com,Female,"Hospitalet De Llobregat, L'",Spain,9289 Merry Circle

In [15]:
df_clientes["gender"].unique()

array(['Female', 'Male', nan, 'Polygender', 'Genderfluid', 'Non-binary',
       'Agender', 'Bigender', 'Genderqueer'], dtype=object)

In [16]:
df_clientes.isnull().sum()

id              0
first_name      0
last_name       0
email          27
gender         77
City          124
Country       154
Address        41
dtype: int64

In [17]:
df_clientes.shape

(1000, 8)

In [18]:
(df_clientes.isnull().sum())/1000

id            0.000
first_name    0.000
last_name     0.000
email         0.027
gender        0.077
City          0.124
Country       0.154
Address       0.041
dtype: float64

In [19]:
((df_clientes.isnull().sum())/1000)*100

id             0.0
first_name     0.0
last_name      0.0
email          2.7
gender         7.7
City          12.4
Country       15.4
Address        4.1
dtype: float64

In [20]:
df_productos.isnull("city")

TypeError: DataFrame.isnull() takes 1 positional argument but 2 were given

In [21]:
df_productos.isnull("City")

TypeError: DataFrame.isnull() takes 1 positional argument but 2 were given

In [22]:
df_productos.isnull(["City"])

TypeError: DataFrame.isnull() takes 1 positional argument but 2 were given

In [23]:
filas_con_nulos = df_clientes[df_clientes['City'].isnull()]

In [24]:
filas_con_nulos = df_clientes[df_clientes['City'].isnull()]
filas_con_nulos

,id,first_name,last_name,email,gender,City,Country,Address
2,3,Michaeline,Paynton,mpaynton2@narod.ru,Female,NaN,Spain,0 Corry Crossing
8,9,Tymon,Darragh,tdarragh8@free.fr,Male,NaN,Spain,41 Trailsway Way
10,11,Chase,Godilington,cgodilingtona@spiegel.de,Male,NaN,NaN,13 Bluestem Court
18,19,Sena,MacElane,smacelanei@youtu.be,Female,NaN,Spain,8032 Claremont Trail
32,33,Adoree,Cutchey,acutcheyw@seesaa.net,NaN,NaN,Spain,917 Marcy Parkway
...,...,...,...,...,...,...,...,...
942,943,Maritsa,Doale,mdoaleq6@google.nl,NaN,NaN,Spain,7 Toban Center
961,962,Domenic,Adger,dadgerqp@time.com,Male,NaN,Spain,327 Gateway Crossing
964,965,Marijn,St Clair,mstclairqs@technorati.com,Male,NaN,Spain,57 Jay Drive
965,966,Didi,Hawtry,dhawtryqt@opensource.org,Female,NaN,Spain,901 Packers Way
986,987,Cecil,Hemms,chemmsre@reverbnation.com,Male,NaN,Spain,1737 Commercial Lane

In [25]:
filas_con_nulos = df_clientes[df_clientes['City'].isnull()]
filas_con_nulos

,id,first_name,last_name,email,gender,City,Country,Address
2,3,Michaeline,Paynton,mpaynton2@narod.ru,Female,NaN,Spain,0 Corry Crossing
8,9,Tymon,Darragh,tdarragh8@free.fr,Male,NaN,Spain,41 Trailsway Way
10,11,Chase,Godilington,cgodilingtona@spiegel.de,Male,NaN,NaN,13 Bluestem Court
18,19,Sena,MacElane,smacelanei@youtu.be,Female,NaN,Spain,8032 Claremont Trail
32,33,Adoree,Cutchey,acutcheyw@seesaa.net,NaN,NaN,Spain,917 Marcy Parkway
...,...,...,...,...,...,...,...,...
942,943,Maritsa,Doale,mdoaleq6@google.nl,NaN,NaN,Spain,7 Toban Center
961,962,Domenic,Adger,dadgerqp@time.com,Male,NaN,Spain,327 Gateway Crossing
964,965,Marijn,St Clair,mstclairqs@technorati.com,Male,NaN,Spain,57 Jay Drive
965,966,Didi,Hawtry,dhawtryqt@opensource.org,Female,NaN,Spain,901 Packers Way
986,987,Cecil,Hemms,chemmsre@reverbnation.com,Male,NaN,Spain,1737 Commercial Lane

In [26]:
filas_con_nulos = df_clientes[df_clientes['City'].isnull()]
filas_con_nulos

,id,first_name,last_name,email,gender,City,Country,Address
2,3,Michaeline,Paynton,mpaynton2@narod.ru,Female,NaN,Spain,0 Corry Crossing
8,9,Tymon,Darragh,tdarragh8@free.fr,Male,NaN,Spain,41 Trailsway Way
10,11,Chase,Godilington,cgodilingtona@spiegel.de,Male,NaN,NaN,13 Bluestem Court
18,19,Sena,MacElane,smacelanei@youtu.be,Female,NaN,Spain,8032 Claremont Trail
32,33,Adoree,Cutchey,acutcheyw@seesaa.net,NaN,NaN,Spain,917 Marcy Parkway
...,...,...,...,...,...,...,...,...
942,943,Maritsa,Doale,mdoaleq6@google.nl,NaN,NaN,Spain,7 Toban Center
961,962,Domenic,Adger,dadgerqp@time.com,Male,NaN,Spain,327 Gateway Crossing
964,965,Marijn,St Clair,mstclairqs@technorati.com,Male,NaN,Spain,57 Jay Drive
965,966,Didi,Hawtry,dhawtryqt@opensource.org,Female,NaN,Spain,901 Packers Way
986,987,Cecil,Hemms,chemmsre@reverbnation.com,Male,NaN,Spain,1737 Commercial Lane

In [27]:
filas_con_nulos = df_clientes[df_clientes['City'].isnull()]
filas_con_nulos

,id,first_name,last_name,email,gender,City,Country,Address
2,3,Michaeline,Paynton,mpaynton2@narod.ru,Female,NaN,Spain,0 Corry Crossing
8,9,Tymon,Darragh,tdarragh8@free.fr,Male,NaN,Spain,41 Trailsway Way
10,11,Chase,Godilington,cgodilingtona@spiegel.de,Male,NaN,NaN,13 Bluestem Court
18,19,Sena,MacElane,smacelanei@youtu.be,Female,NaN,Spain,8032 Claremont Trail
32,33,Adoree,Cutchey,acutcheyw@seesaa.net,NaN,NaN,Spain,917 Marcy Parkway
...,...,...,...,...,...,...,...,...
942,943,Maritsa,Doale,mdoaleq6@google.nl,NaN,NaN,Spain,7 Toban Center
961,962,Domenic,Adger,dadgerqp@time.com,Male,NaN,Spain,327 Gateway Crossing
964,965,Marijn,St Clair,mstclairqs@technorati.com,Male,NaN,Spain,57 Jay Drive
965,966,Didi,Hawtry,dhawtryqt@opensource.org,Female,NaN,Spain,901 Packers Way
986,987,Cecil,Hemms,chemmsre@reverbnation.com,Male,NaN,Spain,1737 Commercial Lane