In [8]:
import pandas as pd 
import numpy as np

In [11]:
#1.Abrid el fichero de rating-and-performance con el método que sea más correcto.
data = pd.read_csv("../files/rating-and-performance.csv", dtype={})

In [12]:
#2. Motrad las 10 ultimas filas
data.tail(10)

,index,title,title_orig,price,retail_price,currency_buyer,units_sold,uses_ad_boosts,rating,rating_count,...,merchant_rating_count,merchant_rating,merchant_id,merchant_has_profile_picture,merchant_profile_picture,product_url,product_picture,product_id,theme,crawl_month
1563,1563,ZANZEA Femmes Été Polka Dot Kaftan Beach Club ...,ZANZEA Women Summer Polka Dot Kaftan Beach Clu...,15.00,92,EUR,100,0,3.51,74,...,151914,4.127921,53aa664438d3046ee44a5024,0,NaN,https://www.wish.com/c/5da04c1f5949a226113006f1,https://contestimg.wish.com/api/webimage/5da04...,5da04c1f5949a226113006f1,summer,2020-08
1564,1564,2018 Femme mode d'été en dentelle Patchwork Pa...,2018 Women fashion Summer Lace Patchwork Tank ...,5.91,5,EUR,1000,0,3.38,414,...,12134,3.866903,58aec90823ef726994a323fe,0,NaN,https://www.wish.com/c/5b4ed29514f0765a8a844592,https://contestimg.wish.com/api/webimage/5b4ed...,5b4ed29514f0765a8a844592,summer,2020-08
1565,1565,Nouveau Pantalon De Mode D'été Femmes Leggings...,New Summer Fashion Trousers Women Leggings Rip...,3.00,8,EUR,100,1,3.79,57,...,4080,3.987990,584a7a381591451e4e3af3df,0,NaN,https://www.wish.com/c/5e8f0165e815903d022a3c7c,https://contestimg.wish.com/api/webimage/5e8f0...,5e8f0165e815903d022a3c7c,summer,2020-08
1566,1566,Robe mi-longue d'été à manches courtes pour fe...,Womens Short Sleeve Baggy Summer Beach Midi Dr...,11.00,134,EUR,100,1,3.54,28,...,1926,4.071651,593402ae25c4f54ed4e0abdf,0,NaN,https://www.wish.com/c/5d1060d39ed281190dfcec91,https://contestimg.wish.com/api/webimage/5d106...,5d1060d39ed281190dfcec91,summer,2020-08
1567,1567,Combinaison sans manches pour femmes couleur u...,Sleeveless Solid Color Women Jumpsuit Ladies S...,8.00,7,EUR,20000,1,4.25,3127,...,16803,4.155032,56455b13b15aab129db58cb7,0,NaN,https://www.wish.com/c/5c91a7ae7cfe8e4e64c36d97,https://contestimg.wish.com/api/webimage/5c91a...,5c91a7ae7cfe8e4e64c36d97,summer,2020-08
1568,1568,Nouvelle Mode Femmes Bohême Pissenlit Imprimer...,New Fashion Women Bohemia Dandelion Print Tee ...,6.00,9,EUR,10000,1,4.08,1367,...,5316,4.224605,5b507899ab577736508a0782,0,NaN,https://www.wish.com/c/5d5fadc99febd9356cbc52ee,https://contestimg.wish.com/api/webimage/5d5fa...,5d5fadc99febd9356cbc52ee,summer,2020-08
1569,1569,10 couleurs femmes shorts d'été lacent ceintur...,10 Color Women Summer Shorts Lace Up Elastic W...,2.00,56,EUR,100,1,3.07,28,...,4435,3.696054,54d83b6b6b8a771e478558de,0,NaN,https://www.wish.com/c/5eccd22b4497b86fd48f16b4,https://contestimg.wish.com/api/webimage/5eccd...,5eccd22b4497b86fd48f16b4,summer,2020-08
1570,1570,Nouveautés Hommes Siwmwear Beach-Shorts Hommes...,New Men Siwmwear Beach-Shorts Men Summer Quick...,5.00,19,EUR,100,0,3.71,59,...,210,3.961905,5b42da1bf64320209fc8da69,0,NaN,https://www.wish.com/c/5e74be96034d613d42b52dfe,https://contestimg.wish.com/api/webimage/5e74b...,5e74be96034d613d42b52dfe,summer,2020-08
1571,1571,Mode femmes d'été sans manches robes col en V ...,Fashion Women Summer Sleeveless Dresses V Neck...,13.00,11,EUR,100,0,2.50,2,...,31,3.774194,5d56b32c40defd78043d5af9,0,NaN,https://www.wish.com/c/5eda07ab0e295c2097c36590,https://contestimg.wish.com/api/webimage/5eda0...,5eda07ab0e295c2097c36590,summer,2020-08
1572,1572,Pantalon de yoga pour femmes à la mode Slim Fi...,Fashion Women Yoga Pants Slim Fit Fitness Runn...,7.00,6,EUR,100,1,4.07,14,...,7023,4.235939,5a409cf87b584e7951b2e25f,0,NaN,https://www.wish.com/c/5e857321f53c3d2d8f25e7ed,https://contestimg.wish.com/api/webimage/5e857...,5e857321f53c3d2d8f25e7ed,summer,2020-08

In [13]:
#3.Mostrad 5 filas aleatorias del DataFrame.

data.sample(5)

,index,title,title_orig,price,retail_price,currency_buyer,units_sold,uses_ad_boosts,rating,rating_count,...,merchant_rating_count,merchant_rating,merchant_id,merchant_has_profile_picture,merchant_profile_picture,product_url,product_picture,product_id,theme,crawl_month
656,656,4 Couleur Été Nouvelles Femmes De Mode À Manch...,4 Color Summer New Women's Fashion Short Sleev...,8.0,7,EUR,100,0,3.43,23,...,24132,4.130946,58ad74688a58e150335088ce,0,NaN,https://www.wish.com/c/5eb4dfbb1284d61c96c43bad,https://contestimg.wish.com/api/webimage/5eb4d...,5eb4dfbb1284d61c96c43bad,summer,2020-08
715,715,Robe décontractée d'été à manches courtes à ma...,Summer New Women's Casual Dress Short Sleeve V...,11.0,10,EUR,100,1,3.80,10,...,247,3.943320,5d5256c527752b19063d8c53,0,NaN,https://www.wish.com/c/5ecb27f2a746691048f27232,https://contestimg.wish.com/api/webimage/5ecb2...,5ecb27f2a746691048f27232,summer,2020-08
267,267,Femmes Mode Sexy Tie Dye Imprimé Deux Pièces E...,Women Fashion Sexy Tie Dye Printed Two Piece S...,13.0,11,EUR,100,1,4.00,4,...,45151,4.032956,5836e38728f25753fe6af6a8,0,NaN,https://www.wish.com/c/5ec3740fa7ed5d2fbc7460a5,https://contestimg.wish.com/api/webimage/5ec37...,5ec3740fa7ed5d2fbc7460a5,summer,2020-08
398,398,Women Fashion Casual Summer Sleeveless Blackle...,Women Fashion Casual Summer Sleeveless Blackle...,8.0,48,EUR,1000,0,4.34,794,...,3403,4.337349,57a155a4b63950286426744f,0,NaN,https://www.wish.com/c/5b17b34f5272053200439a7a,https://contestimg.wish.com/api/webimage/5b17b...,5b17b34f5272053200439a7a,summer,2020-08
1045,1045,16 Color Fashion Women Casual Sleeveless Camis...,16 Color Fashion Women Casual Sleeveless Camis...,7.0,6,EUR,100,0,3.65,20,...,24,3.625000,5dbe8b3a0140ee444c50ec2b,0,NaN,https://www.wish.com/c/5e9e9f8aca869939b544a886,https://contestimg.wish.com/api/webimage/5e9e9...,5e9e9f8aca869939b544a886,summer,2020-08

In [14]:
#4. ¿Cuántas filas y columnas tenemos en el DataFrame?
data.info

<bound method DataFrame.info of       index                                              title  \
0         0  2020 Summer Vintage Flamingo Print  Pajamas Se...
1         1  SSHOUSE Summer Casual Sleeveless Soirée Party ...
2         2  2020 Nouvelle Arrivée Femmes Printemps et Été ...
3         3  Hot Summer Cool T-shirt pour les femmes Mode T...
4         4  Femmes Shorts d'été à lacets taille élastique ...
...     ...                                                ...
1568   1568  Nouvelle Mode Femmes Bohême Pissenlit Imprimer...
1569   1569  10 couleurs femmes shorts d'été lacent ceintur...
1570   1570  Nouveautés Hommes Siwmwear Beach-Shorts Hommes...
1571   1571  Mode femmes d'été sans manches robes col en V ...
1572   1572  Pantalon de yoga pour femmes à la mode Slim Fi...

                                             title_orig  price  retail_price  \
0     2020 Summer Vintage Flamingo Print  Pajamas Se...  16.00            14
1      Women's Casual Summer Sleeveless Sexy Mini Dress   8.00            22
2     2020 New Arrival Women Spring and Summer Beach...   8.00            43
3     Hot Summer Cool T Shirt for Women Fashion Tops...   8.00             8
4     Women Summer Shorts Lace Up Elastic Waistband ...   2.72             3
...                                                 ...    ...           ...
1568  New Fashion Women Bohemia Dandelion Print Tee ...   6.00             9
1569  10 Color Women Summer Shorts Lace Up Elastic W...   2.00            56
1570  New Men Siwmwear Beach-Shorts Men Summer Quick...   5.00            19
1571  Fashion Women Summer Sleeveless Dresses V Neck...  13.00            11
1572  Fashion Women Yoga Pants Slim Fit Fitness Runn...   7.00             6

     currency_buyer  units_sold  uses_ad_boosts  rating  rating_count  ...  \
0               EUR         100               0    3.76            54  ...
1               EUR       20000               1    3.45          6135  ...
2               EUR         100               0    3.57            14  ...
3               EUR        5000               1    4.03           579  ...
4               EUR         100               1    3.10            20  ...
...             ...         ...             ...     ...           ...  ...
1568            EUR       10000               1    4.08          1367  ...
1569            EUR         100               1    3.07            28  ...
1570            EUR         100               0    3.71            59  ...
1571            EUR         100               0    2.50             2  ...
1572            EUR         100               1    4.07            14  ...

      merchant_rating_count  merchant_rating               merchant_id  \
0                       568         4.128521  595097d6a26f6e070cb878d1
1                     17752         3.899673  56458aa03a698c35c9050988
2                       295         3.989831  5d464a1ffdf7bc44ee933c65
3                     23832         4.020435  58cfdefdacb37b556efdff7c
4                     14482         4.001588  5ab3b592c3911a095ad5dadb
...                     ...              ...                       ...
1568                   5316         4.224605  5b507899ab577736508a0782
1569                   4435         3.696054  54d83b6b6b8a771e478558de
1570                    210         3.961905  5b42da1bf64320209fc8da69
1571                     31         3.774194  5d56b32c40defd78043d5af9
1572                   7023         4.235939  5a409cf87b584e7951b2e25f

      merchant_has_profile_picture  merchant_profile_picture  \
0                                0                       NaN
1                                0                       NaN
2                                0                       NaN
3                                0                       NaN
4                                0                       NaN
...                            ...                       ...
1568                             0                       NaN
1569                             0                       NaN
1570                             0                       NaN
1571                             0                       NaN
1572                             0                       NaN

                                          product_url  \
0     https://www.wish.com/c/5e9ae51d43d6a96e303acdb0
1     https://www.wish.com/c/58940d436a0d3d5da4e95a38
2     https://www.wish.com/c/5ea10e2c617580260d55310a
3     https://www.wish.com/c/5cedf17ad1d44c52c59e4aca
4     https://www.wish.com/c/5ebf5819ebac372b070b0e70
...                                               ...
1568  https://www.wish.com/c/5d5fadc99febd9356cbc52ee
1569  https://www.wish.com/c/5eccd22b4497b86fd48f16b4
1570  https://www.wish.com/c/5e74be96034d613d42b52dfe
1571  https://www.wish.com/c/5eda07ab0e295c2097c36590
1572  https://www.wish.com/c/5e857321f53c3d2d8f25e7ed

                                        product_picture  \
0     https://contestimg.wish.com/api/webimage/5e9ae...
1     https://contestimg.wish.com/api/webimage/58940...
2     https://contestimg.wish.com/api/webimage/5ea10...
3     https://contestimg.wish.com/api/webimage/5cedf...
4     https://contestimg.wish.com/api/webimage/5ebf5...
...                                                 ...
1568  https://contestimg.wish.com/api/webimage/5d5fa...
1569  https://contestimg.wish.com/api/webimage/5eccd...
1570  https://contestimg.wish.com/api/webimage/5e74b...
1571  https://contestimg.wish.com/api/webimage/5eda0...
1572  https://contestimg.wish.com/api/webimage/5e857...

                    product_id   theme crawl_month
0     5e9ae51d43d6a96e303acdb0  summer     2020-08
1     58940d436a0d3d5da4e95a38  summer     2020-08
2     5ea10e2c617580260d55310a  summer     2020-08
3     5cedf17ad1d44c52c59e4aca  summer     2020-08
4     5ebf5819ebac372b070b0e70  summer     2020-08
...                        ...     ...         ...
1568  5d5fadc99febd9356cbc52ee  summer     2020-08
1569  5eccd22b4497b86fd48f16b4  summer     2020-08
1570  5e74be96034d613d42b52dfe  summer     2020-08
1571  5eda07ab0e295c2097c36590  summer     2020-08
1572  5e857321f53c3d2d8f25e7ed  summer     2020-08

[1573 rows x 44 columns]>

In [17]:
#4.¿Cuantas filas y columnas hay?
data.shape

(1573, 44)

In [21]:
#5. ¿Cuáles son los nombres de las columnas del DataFrame?
data.columns

Index(['index', 'title', 'title_orig', 'price', 'retail_price',
       'currency_buyer', 'units_sold', 'uses_ad_boosts', 'rating',
       'rating_count', 'rating_five_count', 'rating_four_count',
       'rating_three_count', 'rating_two_count', 'rating_one_count',
       'badges_count', 'badge_local_product', 'badge_product_quality',
       'badge_fast_shipping', 'tags', 'product_color',
       'product_variation_size_id', 'product_variation_inventory',
       'shipping_option_name', 'shipping_option_price', 'shipping_is_express',
       'countries_shipped_to', 'inventory_total', 'has_urgency_banner',
       'urgency_text', 'origin_country', 'merchant_title', 'merchant_name',
       'merchant_info_subtitle', 'merchant_rating_count', 'merchant_rating',
       'merchant_id', 'merchant_has_profile_picture',
       'merchant_profile_picture', 'product_url', 'product_picture',
       'product_id', 'theme', 'crawl_month'],
      dtype='object')

In [24]:
#6.Seleccionad solo las columnas de tipo categórico del DataFrame. 
data.select_dtypes(include="category")
data.dtypes

index                             int64
title                            object
title_orig                       object
price                           float64
retail_price                      int64
currency_buyer                   object
units_sold                        int64
uses_ad_boosts                    int64
rating                          float64
rating_count                      int64
rating_five_count               float64
rating_four_count               float64
rating_three_count              float64
rating_two_count                float64
rating_one_count                float64
badges_count                      int64
badge_local_product               int64
badge_product_quality             int64
badge_fast_shipping               int64
tags                             object
product_color                    object
product_variation_size_id        object
product_variation_inventory       int64
shipping_option_name             object
shipping_option_price             int64
shipping_is_express               int64
countries_shipped_to              int64
inventory_total                   int64
has_urgency_banner              float64
urgency_text                     object
origin_country                   object
merchant_title                   object
merchant_name                    object
merchant_info_subtitle           object
merchant_rating_count             int64
merchant_rating                 float64
merchant_id                      object
merchant_has_profile_picture      int64
merchant_profile_picture         object
product_url                      object
product_picture                  object
product_id                       object
theme                            object
crawl_month                      object
dtype: object

In [28]:
# Después, mostrad los valores únicos y sus frecuencias para cada una de las columnas seleccionadas.
data.nunique

<bound method DataFrame.nunique of       index                                              title  \
0         0  2020 Summer Vintage Flamingo Print  Pajamas Se...
1         1  SSHOUSE Summer Casual Sleeveless Soirée Party ...
2         2  2020 Nouvelle Arrivée Femmes Printemps et Été ...
3         3  Hot Summer Cool T-shirt pour les femmes Mode T...
4         4  Femmes Shorts d'été à lacets taille élastique ...
...     ...                                                ...
1568   1568  Nouvelle Mode Femmes Bohême Pissenlit Imprimer...
1569   1569  10 couleurs femmes shorts d'été lacent ceintur...
1570   1570  Nouveautés Hommes Siwmwear Beach-Shorts Hommes...
1571   1571  Mode femmes d'été sans manches robes col en V ...
1572   1572  Pantalon de yoga pour femmes à la mode Slim Fi...

                                             title_orig  price  retail_price  \
0     2020 Summer Vintage Flamingo Print  Pajamas Se...  16.00            14
1      Women's Casual Summer Sleeveless Sexy Mini Dress   8.00            22
2     2020 New Arrival Women Spring and Summer Beach...   8.00            43
3     Hot Summer Cool T Shirt for Women Fashion Tops...   8.00             8
4     Women Summer Shorts Lace Up Elastic Waistband ...   2.72             3
...                                                 ...    ...           ...
1568  New Fashion Women Bohemia Dandelion Print Tee ...   6.00             9
1569  10 Color Women Summer Shorts Lace Up Elastic W...   2.00            56
1570  New Men Siwmwear Beach-Shorts Men Summer Quick...   5.00            19
1571  Fashion Women Summer Sleeveless Dresses V Neck...  13.00            11
1572  Fashion Women Yoga Pants Slim Fit Fitness Runn...   7.00             6

     currency_buyer  units_sold  uses_ad_boosts  rating  rating_count  ...  \
0               EUR         100               0    3.76            54  ...
1               EUR       20000               1    3.45          6135  ...
2               EUR         100               0    3.57            14  ...
3               EUR        5000               1    4.03           579  ...
4               EUR         100               1    3.10            20  ...
...             ...         ...             ...     ...           ...  ...
1568            EUR       10000               1    4.08          1367  ...
1569            EUR         100               1    3.07            28  ...
1570            EUR         100               0    3.71            59  ...
1571            EUR         100               0    2.50             2  ...
1572            EUR         100               1    4.07            14  ...

      merchant_rating_count  merchant_rating               merchant_id  \
0                       568         4.128521  595097d6a26f6e070cb878d1
1                     17752         3.899673  56458aa03a698c35c9050988
2                       295         3.989831  5d464a1ffdf7bc44ee933c65
3                     23832         4.020435  58cfdefdacb37b556efdff7c
4                     14482         4.001588  5ab3b592c3911a095ad5dadb
...                     ...              ...                       ...
1568                   5316         4.224605  5b507899ab577736508a0782
1569                   4435         3.696054  54d83b6b6b8a771e478558de
1570                    210         3.961905  5b42da1bf64320209fc8da69
1571                     31         3.774194  5d56b32c40defd78043d5af9
1572                   7023         4.235939  5a409cf87b584e7951b2e25f

      merchant_has_profile_picture  merchant_profile_picture  \
0                                0                       NaN
1                                0                       NaN
2                                0                       NaN
3                                0                       NaN
4                                0                       NaN
...                            ...                       ...
1568                             0                       NaN
1569                             0                       NaN
1570                             0                       NaN
1571                             0                       NaN
1572                             0                       NaN

                                          product_url  \
0     https://www.wish.com/c/5e9ae51d43d6a96e303acdb0
1     https://www.wish.com/c/58940d436a0d3d5da4e95a38
2     https://www.wish.com/c/5ea10e2c617580260d55310a
3     https://www.wish.com/c/5cedf17ad1d44c52c59e4aca
4     https://www.wish.com/c/5ebf5819ebac372b070b0e70
...                                               ...
1568  https://www.wish.com/c/5d5fadc99febd9356cbc52ee
1569  https://www.wish.com/c/5eccd22b4497b86fd48f16b4
1570  https://www.wish.com/c/5e74be96034d613d42b52dfe
1571  https://www.wish.com/c/5eda07ab0e295c2097c36590
1572  https://www.wish.com/c/5e857321f53c3d2d8f25e7ed

                                        product_picture  \
0     https://contestimg.wish.com/api/webimage/5e9ae...
1     https://contestimg.wish.com/api/webimage/58940...
2     https://contestimg.wish.com/api/webimage/5ea10...
3     https://contestimg.wish.com/api/webimage/5cedf...
4     https://contestimg.wish.com/api/webimage/5ebf5...
...                                                 ...
1568  https://contestimg.wish.com/api/webimage/5d5fa...
1569  https://contestimg.wish.com/api/webimage/5eccd...
1570  https://contestimg.wish.com/api/webimage/5e74b...
1571  https://contestimg.wish.com/api/webimage/5eda0...
1572  https://contestimg.wish.com/api/webimage/5e857...

                    product_id   theme crawl_month
0     5e9ae51d43d6a96e303acdb0  summer     2020-08
1     58940d436a0d3d5da4e95a38  summer     2020-08
2     5ea10e2c617580260d55310a  summer     2020-08
3     5cedf17ad1d44c52c59e4aca  summer     2020-08
4     5ebf5819ebac372b070b0e70  summer     2020-08
...                        ...     ...         ...
1568  5d5fadc99febd9356cbc52ee  summer     2020-08
1569  5eccd22b4497b86fd48f16b4  summer     2020-08
1570  5e74be96034d613d42b52dfe  summer     2020-08
1571  5eda07ab0e295c2097c36590  summer     2020-08
1572  5e857321f53c3d2d8f25e7ed  summer     2020-08

[1573 rows x 44 columns]>

In [31]:
#7.En el DataFrame tenemos dos columnas que parece que nos dan la misma información "title" y "title_orig". Eliminad "title".
data.pop("title")

KeyError: 'title'

In [32]:
data.columns

Index(['index', 'title_orig', 'price', 'retail_price', 'currency_buyer',
       'units_sold', 'uses_ad_boosts', 'rating', 'rating_count',
       'rating_five_count', 'rating_four_count', 'rating_three_count',
       'rating_two_count', 'rating_one_count', 'badges_count',
       'badge_local_product', 'badge_product_quality', 'badge_fast_shipping',
       'tags', 'product_color', 'product_variation_size_id',
       'product_variation_inventory', 'shipping_option_name',
       'shipping_option_price', 'shipping_is_express', 'countries_shipped_to',
       'inventory_total', 'has_urgency_banner', 'urgency_text',
       'origin_country', 'merchant_title', 'merchant_name',
       'merchant_info_subtitle', 'merchant_rating_count', 'merchant_rating',
       'merchant_id', 'merchant_has_profile_picture',
       'merchant_profile_picture', 'product_url', 'product_picture',
       'product_id', 'theme', 'crawl_month'],
      dtype='object')

In [33]:
#8.¿En que columnas tenemos valores nulos? Utilizad el método que más os guste.
data.isnull().sum()

index                              0
title_orig                         0
price                              0
retail_price                       0
currency_buyer                     0
units_sold                         0
uses_ad_boosts                     0
rating                             0
rating_count                       0
rating_five_count                 45
rating_four_count                 45
rating_three_count                45
rating_two_count                  45
rating_one_count                  45
badges_count                       0
badge_local_product                0
badge_product_quality              0
badge_fast_shipping                0
tags                               0
product_color                     41
product_variation_size_id         14
product_variation_inventory        0
shipping_option_name               0
shipping_option_price              0
shipping_is_express                0
countries_shipped_to               0
inventory_total                    0
has_urgency_banner              1100
urgency_text                    1100
origin_country                    17
merchant_title                     0
merchant_name                      4
merchant_info_subtitle             1
merchant_rating_count              0
merchant_rating                    0
merchant_id                        0
merchant_has_profile_picture       0
merchant_profile_picture        1347
product_url                        0
product_picture                    0
product_id                         0
theme                              0
crawl_month                        0
dtype: int64

In [34]:
#9.¿Tenemos valores duplicados en el DataFrame?
data.duplicated().sum()

0